### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by Nathalie-Kaestner** [Nathalie-Kaestner/htw-se-example-teamproject-#3]
Da steht nix drin oder bin ich blöd?

**Comment by AnswerThirtyTwo** [comment]
Da steht nichts drin, das es dafür gedacht ist, dass diese Git Datei dafür sorgt das HTML- und PDF Dateien im Verzeichnis ignoriert werden und so nicht in betracht gezogen werden.

**Comment by Nathalie-Kaestner** [comment]
alles paletti
